version: "3.7"
services:

  # Antivirus
  antivirus:
    container_name: edivorce-antivirus
    hostname: antivirus
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310"
    restart: unless-stopped

  # Redis Server
  redis:
    container_name: edivorce-redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: unless-stopped

  # Weasyprint (PDF generator)
  weasyprint:
    container_name: edivorce-weasyprint
    hostname: weasyprint
    image: aquavitae/weasyprint
    ports:
      - "5005:5001"
    restart: unless-stopped


volumes:
  data-redis:
