version: "3.7"
services:

  # Antivirus
  antivirus:
    container_name: edivorce-antivirus
    hostname: antivirus
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310"
    restart: unless-stopped

  # Redis Server
  redis:
    container_name: edivorce-redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: unless-stopped

  # Weasyprint (PDF generator)
  weasyprint:
    container_name: edivorce-weasyprint
    hostname: weasyprint
    image: aquavitae/weasyprint
    ports:
      - "5005:5001"
    restart: unless-stopped

  # Keycloak
  keycloak:
    container_name: edivorce-keycloak
    image: jboss/keycloak:9.0.3
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./conf/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 8081:8080
    command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    restart: unless-stopped    

volumes:
  data-redis:
