# Generated by Django 3.2.16 on 2022-11-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_guid_as_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bceiduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
