# Generated by Django 2.2.27 on 2022-03-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_no_prov_abbrev'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM core_userresponse WHERE bceid_user_id IN (SELECT bceid_user_id FROM core_userresponse WHERE question_id = 'where_were_you_married_country' AND value='USA') AND question_id = 'where_were_you_married_other_country'"),
        migrations.RunSQL("INSERT INTO core_userresponse (value, bceid_user_id, question_id) SELECT 'USA' AS value, bceid_user_id, 'where_were_you_married_other_country' AS question_id FROM core_userresponse WHERE question_id = 'where_were_you_married_country' AND value='USA'"),
        migrations.RunSQL("UPDATE core_userresponse SET value = 'Other' WHERE question_id = 'where_were_you_married_country' AND value='USA'")
    ]
