# Generated by Django 3.2.16 on 2023-02-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_bceiduser_first_name'),
        ('core', '0032_change_usa_to_other'),
    ]

    operations = [
    ]
